import type { SetupTrack } from '../types/accountProfile';

export type AuthStackParamList = {
  Welcome: undefined;
  Register: undefined;
  Login: undefined;
};

export type AppStackParamList = {
  IntentSelect: undefined;
  BrowseHome: undefined;
  StudentHome: undefined;
  ExploreHome: undefined;
  HostHome: undefined;
  GuideHome: undefined;
  Profile: undefined;
  DevTesting: undefined;
  AccountSetup: undefined;
  UnifiedSearch: undefined;
  Destination: { track: 'SEEKER' };
  StudentQuiz: { track: 'SEEKER' };
  HostQuiz: { track: 'HOST' };
  TouristQuiz: { track: 'SEEKER' };
  GuideQuiz: { track: 'GUIDE' };
  ProfileSetup: { track: SetupTrack };
  KYCPrompt: { track: 'HOST' | 'GUIDE' };
  OnboardingReady: { track: SetupTrack };
  StudentBookings: undefined;
  MatchSearch: undefined;
  HostRequestsTab: undefined;
  HostBookingsTab: undefined;
  HostEarningsTab: undefined;
  GuideBookingsTab: undefined;
  GuideEarningsTab: undefined;
  MessagesTab: undefined;
  Chat: { conversationId: string };
  HostProfile: { hostId: string };
  Booking: { hostId: string; bookingContext?: import('../types/booking').BookingContext };
  BookingConfirmed: { bookingId: string };
  GuideSearch: undefined;
  GuideProfile: { guideId: string };
  SessionBooking: { guideId: string; bookingContext?: import('../types/booking').BookingContext };
  LodgingDirectory: undefined;
  LodgingDetail: { listingId: string };
  IncomingRequests: undefined;
  IncomingSessionRequests: undefined;
  MatchRequestReview: { requestId: string };
  SessionReview: { requestId: string };
  SOS: undefined;
  TouristSiteDetail: { siteId: string };
  PrepChecklist: undefined;
  LocalTips: undefined;
  TransportGuide: undefined;
  ExploreStays: undefined;
  OfflineMap: undefined;
  HostCalendar: undefined;
  HostListings: undefined;
  TourTypesSetup: undefined;
  GuideAvailability: undefined;
  SitesDirectory: undefined;
  StudentEvents: undefined;
  CreateEvent: undefined;
  VideoLibrary: undefined;
  VideoDetail: { videoKey: string };
  SponsorList: undefined;
  SponsorDetail: { sponsorId: string };
  SponsorApplication: { sponsorId: string };
  WelfareCheckIn: { bookingId: string };
  ReviewPrompt: { bookingId: string; hostName: string };
};

export type RootStackParamList = {
  Splash: undefined;
  Auth: undefined;
  App: undefined;
};
